status:
  banned: "BANNED"
  unregistered: "UNREGISTERED"

messages:
  greetings:
    to_unregistered_users: "<b>%s\nПривествуем</b>,\nЧтобы начать пользоваться ботом, Вам необходимо пройти <i>регистрацию</i>\nприступим?"
    to_banned_users: "Уважаемый <b>%s</b>, Вы нарушили правила нашего бота, за что получили наказние. Вы можете обратиться в <b><i>службу поддержки</i></b>, чтобы подать аппеляцию."
